name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        dotnet:
          - 7.x

    steps:
    - uses: actions/checkout@v2
    
    - name: dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: build
      run: dotnet build --configuration Release
