name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- uses: actions/setup-node@master
    
    #- name: npm install
    #  working-directory: ./dashboard
    #  run: npm install
      
    #- name: npm build
    #  working-directory: ./dashboard
    #  run: npm run build

    #- name: copy vue dist to aspnetcore
    #  run: cp -Rf ./dashboard/dist/* ./Core.TaskProcessor.Dashboard/static/
    
    - name: dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x
    
    - name: build
      run: dotnet build --configuration Release
